### ISSUE TITLE
We need 404s and any other url page error

### ISSUE THREAD

**Issue by robertkibet** [credmark/credmark-model-framework-py#130]

**Comment by robertkibet** [comment]
We already have the functionality in place, but we just need a nice looking page design for it, right now it will show you an empty white screen page when you hit a 404 error.
@MattCMK  

See screenshot below.


![image](https://user-images.githubusercontent.com/20405825/176592592-8c5b9942-c111-486e-9f9e-83a9fa027fac.png)

**Comment by MattCMK** [comment]
@robertkibet will you reopen this one or should it remain closed?

**Comment by robertkibet** [comment]
@MattCMK I have reopened it in credmark platform, I noticed I created it in credmark model 😅, sorry about that, had to close it

**Comment by MattCMK** [comment]
@robertkibet ah ok understood - thanks man 👍
