### ISSUE TITLE
Manual/userguides requiring no technical knowledge to access the data

### ISSUE THREAD

**Issue by atulemis** [credmark/credmark-model-framework-py#47]
**Issue:**
Tried to follow the manual for installing the Model Framework but couldn't as it assumes high development skills.

**Solution**
The manual procedure requires low to no development skills. Manual covering both OS and Windows machines recommended setups so that it's possible to download and run models from Model Framework.

**Preliminary Feedback**
**IR:** Is this for model consumers? If so, I agree. We need to think more about our customers -- the consumers of the models/data. Don't forget the customers!
**AT:** Yes, this is for model consumers or experienced financial professionals that just start to build coding skills.

**Comment by iwyrkore** [comment]
There is now a `credmark-client` package that can be installed and used to run models. See https://developer-docs.credmark.com/en/latest/api.html#api-client-for-consumers
