### ISSUE TITLE
Running financial model in Model Framework

### ISSUE THREAD

**Issue by atulemis** [credmark/credmark-model-framework-py#48]
**Issue**
Ambiguity in terms of how financial models have to be built in Model Framework.

**Solution**
Approved financial model

Approval includes:
- model input data is correct and reconciled where appropriate
- logic and outputs testing
- implementation is aligned with the Model Framework vision

**Feedback**
- Notes from Kunlun: implemented var-engine as newer design (in PR)
- NZ: best practices are to be verbose and use the internal functions as much as possible. we can certainly start documenting best practices and we should
- IR: And the model itself, input and output should be well documented with doc strings, schema descriptions.
- AT: It's best if we have an approved and running best practice financial model. Once it's done, documentation could be built around it.

**Comment by leafyoung** [comment]
Ambiguous ticket - close
