### ISSUE TITLE
Source field for DTO

### ISSUE THREAD

**Issue by leafyoung** [credmark/credmark-model-framework-py#52]
Could we add a src field to all DTO to be the slug that output it?

**Comment by iwyrkore** [comment]
I don't think that should be in the DTO generally. @newtectonics

**Comment by leafyoung** [comment]
This is one of the ideas to help knowing about the data flow by tracing the modles' output. This may not be the specific solution. Open for ideas.

**Comment by iwyrkore** [comment]
I guess it depends how/why/when the trace is used. In general, a model calling another model will transform its output and return some transformation so the src of the called model will be lost.
