### ISSUE TITLE
credmark-dev console mode

### ISSUE THREAD

**Issue by leafyoung** [credmark/credmark-model-framework-py#79]
a CLI environment with Contract/Token/BlockNumber ready for experiment.
We may also expose the interface from `self.context.models` to query the list of available models, with their input and output.
By calling itself, we can jump to any prior block numbers.

**Comment by iwyrkore** [comment]
Sounds good.

For the list of models, the context has the model loader. To get the list from the server, the context api can be used. Maybe we can just add a `context.list_models()` method.

**Comment by iwyrkore** [comment]
Adding autocomplete for models.
