### ISSUE TITLE
credmark-dev to check latest version - remind user to update

### ISSUE THREAD

**Issue by leafyoung** [credmark/credmark-model-framework-py#95]

**Comment by iwyrkore** [comment]
We can have a script that gets the latest version tag from credmark-model-framework-py (see https://stackoverflow.com/questions/8055029/is-there-a-simple-way-to-git-describe-a-remote-repository/13619380#13619380) but that is dependent on awk. We could also use python to run the `git ls-remote` command an parse the output to find the latest tag.

Not sure this is high priority.

**Comment by leafyoung** [comment]
I ran into a few occasions with our clients that their models showing error because they updated the models-py repository but did not have the latest version of framework installed. A note when they start `credmark-dev` will be helpful.

**Comment by iwyrkore** [comment]
Doing `credmark-dev version` will warn user if the latest version is not installed

https://github.com/credmark/credmark-model-framework-py/pull/125
